version: '3.8'

services:
  phonebook-app:
    build: .
    ports:
      - "8080:8080"

    depends_on:
      - phonebook-db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://phonebook-db:5432/phonebook_db
      SPRING_DATASOURCE_USERNAME: server
      SPRING_DATASOURCE_PASSWORD: Password6767

  phonebook-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: phonebook_db
      POSTGRES_USER: server
      POSTGRES_PASSWORD: Password6767
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: